### ISSUE TITLE
practica 1

### ISSUE THREAD

**Issue by Litzy-12** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Litzy-12#2]
[Practica1_Litzy.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Litzy-12/files/6173449/Practica1_Litzy.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
